#!/usr/bin/env php
<?php

$targetDir = getcwd() . '/config';

if (!is_dir($targetDir)) {
    mkdir($targetDir, 0777, true);
}

$sourceFile = __DIR__ . '/src/Config/config.php';
$targetFile = "$targetDir/cache.php";

if (!file_exists($targetFile)) {
    copy($sourceFile, $targetFile);
    echo "Configuration file created at $targetFile.\n";
} else {
    echo "Configuration file already exists at $targetFile.\n";
}

// Create .cache directory if it doesn't exist
$cacheDir = getcwd() . '/.cache';

if (!is_dir($cacheDir)) {
    mkdir($cacheDir, 0777, true);
}

// create database.sqlite and .gitignore if they don't exist
$databaseFile = "$cacheDir/database.sqlite";
$gitignoreFile = "$cacheDir/.gitignore";

if (!file_exists($databaseFile)) {
    touch($databaseFile);
    echo "Database file created at $databaseFile.\n";
} else {
    echo "Database file already exists at $databaseFile.\n";
}

if (!file_exists($gitignoreFile)) {
    touch($gitignoreFile);

    file_put_contents(
        $gitignoreFile,
        <<<'EOT'
        database.sqlite
        .cache/*
        EOT
    );

    echo "Gitignore file created at $gitignoreFile.\n";
} else {
    echo "Gitignore file already exists at $gitignoreFile.\n";
}

exit(0);
